name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.13.3
      uses: actions/setup-python@v1
      with:
        python-version: '3.13.3'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        make install
        python -m pip install pylint

    - name: Verify Pylint Installation
      run: |
        source .venv/bin/activate
        pylint --version

    - name: Lint with pylint, black, and isort
      run: |
        source .venv/bin/activate
        make lint

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        make test

    - name: Format with black and isort
      run: |
        source .venv/bin/activate
        make format
